# Generated by Django 6.0.5 on 2026-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_question_votes_vote_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
